// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuSI6NPBA2VlZbaAK1m4SE4pi2YGTi3Z4',
    appId: '1:126167070586:web:d58ac03dcec0c1d60b48c3',
    messagingSenderId: '126167070586',
    projectId: 'go-gourmet-alpha',
    authDomain: 'go-gourmet-alpha.firebaseapp.com',
    storageBucket: 'go-gourmet-alpha.firebasestorage.app',
    measurementId: 'G-063HDLFT3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5qz-PZdGygFMFj3qoFLRVUceIk7SIWh8',
    appId: '1:126167070586:android:6f09dcfcaa094bc20b48c3',
    messagingSenderId: '126167070586',
    projectId: 'go-gourmet-alpha',
    storageBucket: 'go-gourmet-alpha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlprrskmSAJTphLm0PjgFTpIuZS2a3kDw',
    appId: '1:126167070586:ios:7a92cdbeb043171d0b48c3',
    messagingSenderId: '126167070586',
    projectId: 'go-gourmet-alpha',
    storageBucket: 'go-gourmet-alpha.firebasestorage.app',
    iosBundleId: 'com.example.billingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlprrskmSAJTphLm0PjgFTpIuZS2a3kDw',
    appId: '1:126167070586:ios:7a92cdbeb043171d0b48c3',
    messagingSenderId: '126167070586',
    projectId: 'go-gourmet-alpha',
    storageBucket: 'go-gourmet-alpha.firebasestorage.app',
    iosBundleId: 'com.example.billingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuSI6NPBA2VlZbaAK1m4SE4pi2YGTi3Z4',
    appId: '1:126167070586:web:6a649164f5c98bd60b48c3',
    messagingSenderId: '126167070586',
    projectId: 'go-gourmet-alpha',
    authDomain: 'go-gourmet-alpha.firebaseapp.com',
    storageBucket: 'go-gourmet-alpha.firebasestorage.app',
    measurementId: 'G-JX3KJGTFD9',
  );
}
